name: Build and push to ACR
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build and push to ACR 
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.IMAGE_TAG }}:${{ github.sha }} .
        docker push ${{ secrets.IMAGE_TAG }}:${{ github.sha }}